version: "3.8"

services:
  # lambda-fastapi-prod:
  #   build:
  #     context: .
  #     dockerfile: ./compose/prod/Dockerfile
  #   container_name: lambda-fastapi-prod
  #   env_file:
  #    - ./config.env
  #   ports:
  #     - 9000:8080

  lambda-fastapi-dev:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    container_name: lambda-fastapi-dev
    env_file:
     - ./config.env
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 5010:5010